### ISSUE TITLE
[Bug] NunchakuFluxDiT Loader Error

### ISSUE THREAD

**Issue by lunatico67** [mit-han-lab/ComfyUI-nunchaku#385]
### Checklist

- [ ] 1. I have searched for related issues and FAQs (https://github.com/mit-han-lab/nunchaku/blob/main/docs/faq.md) but was unable to find a solution.
- [ ] 2. The issue persists in the latest version.
- [ ] 3. Please note that without environment information and a minimal reproducible example, it will be difficult for us to reproduce and address the issue, which may delay our response.
- [ ] 4. If your report is a question rather than a bug, please submit it as a discussion at https://github.com/mit-han-lab/ComfyUI-nunchaku/discussions/new/choose. Otherwise, this issue will be closed.
- [ ] 5. I will do my best to describe the issue in English.

### Describe the Bug

<img width="624" height="512" alt="Image" src="https://github.com/user-attachments/assets/baca8aa1-7d4b-4daf-bfec-4ad521592d89" />
<img width="684" height="534" alt="Image" src="https://github.com/user-attachments/assets/e5e80851-046e-4e58-99da-9d2fe99c8e15" />

### Environment

I don,t know

### Reproduction Steps

<img width="624" height="512" alt="Image" src="https://github.com/user-attachments/assets/c6ecc5fb-07ab-4d8e-a81e-d22ac3e7f8c9" />
<img width="684" height="534" alt="Image" src="https://github.com/user-attachments/assets/72422a5b-d344-415f-a9b7-3fa6f984fd7c" />

**Comment by Sweborn** [comment]
You need to have all required models installed to make the node apare correctly. You can see the missing models in the ComfyUI's startup log.

**Comment by untitled108** [comment]
my issue was compatibilities. after upgrading/downgrading accordingly it worked.

**Comment by smh2287** [comment]
what did you upgrade and downgrade in order to solve the problem? I have the same issue

**Comment by untitled108** [comment]
> what did you upgrade and downgrade in order to solve the problem? I have the same issue

check the console for where things went wrong. @Sweborn this is the way.

**Comment by lmxyy** [comment]
Have you fixed this? It is very likely that nunchaku wheel is not installed properly. Could you try this [workflow](https://nunchaku.tech/docs/ComfyUI-nunchaku/workflows/tools.html#install-wheel-json)? Could you also share you log? The error information should embraced by

```
=======ComfyUI-nunchaku Initialization=====
....
```

**Comment by MugenMan** [comment]
>Could you try this

I had the same problem.
The solution in the link with installation via wf helped (i installed v0.3.1), thank you!

The console previously displayed the following errors:
`======================================== ComfyUI-nunchaku Initialization ========================================
Nunchaku version: Package 'nunchaku' not found.
ComfyUI-nunchaku version: 0.3.3
ComfyUI-nunchaku 0.3.3 is not compatible with nunchaku Package 'nunchaku' not found.. Please update nunchaku to a supported version in ['v0.3.1'].
Node `NunchakuFluxDiTLoader` import failed:`

**Comment by lmxyy** [comment]
could you install nunchaku wheel with this [workflow](https://nunchaku.tech/docs/ComfyUI-nunchaku/workflows/tools.html#install-wheel-json)?

**Comment by BoynChan** [comment]
For some might encountered this issue. My solution:
- Check ComfyUI startup logs
- Found some errors on init nunchaku nodes. For me, is peft version too low. 
- Install these dependencies.
- Fixed.

<img width="2270" height="254" alt="Image" src="https://github.com/user-attachments/assets/0b31c083-c6f4-47d8-bfc8-65466b17a5da" />

**Comment by squire456** [comment]
my issue is that it it didn't work due to broken symlinks inside the diffusion model. I had to move those outside the folder for it to work.

**Comment by drelabre** [comment]
@lmxyy Had similar issue with nodes not loading. Downloaded the wheel.json to download the right wheel (needed to get 0.3.1) and it's working now. Thank you.

**Comment by zlchs131QQ** [comment]
> For some might encountered this issue. My solution:
> 
> * Check ComfyUI startup logs
> * Found some errors on init nunchaku nodes. For me, is peft version too low.
> * Install these dependencies.
> * Fixed.

HI, how do you update your peft? i got same problem peft =14, but when i update in "python_embeded" floder and type "pip install "peft>=0.15.0", it shows peft is 0.17.0, but when i restart comfyui, still the same peft=14 error, why? thanks

**Comment by lmxyy** [comment]
> > For some might encountered this issue. My solution:
> > 
> > * Check ComfyUI startup logs
> > * Found some errors on init nunchaku nodes. For me, is peft version too low.
> > * Install these dependencies.
> > * Fixed.
> 
> HI, how do you update your peft? i got same problem peft =14, but when i update in "python_embeded" floder and type "pip install "peft>=0.15.0", it shows peft is 0.17.0, but when i restart comfyui, still the same peft=14 error, why? thanks

I think you are using 秋叶启动器. If so, please disable auto version fix.

**Comment by xueqing0622** [comment]
if there is other checkpoints missing like HardLinkShellExt mistake, also will occur this error.
